"use client"
import { useEffect, useState } from "react"
import { Feather, Search } from "lucide-react"
import { AnonymousInput } from "@/components/anonymous-input"
import { PostCard } from "@/components/digitazyl/post-card"
import { SiteHeader } from "@/components/digitazyl/site-header"
import { SafetyBar } from "@/components/digitazyl/safety-bar"
import { categoryLabels, defaultPost, demoPosts, readStorage, storageKeys, writeStorage, type Post, type PostCategory } from "@/lib/data/types"

export default function Home() { const [text, setText] = useState(""); const [latest, setLatest] = useState<Post>(defaultPost); const [category, setCategory] = useState<"všechno" | PostCategory>("všechno"); const [query, setQuery] = useState("");
 useEffect(() => { setLatest(readStorage(storageKeys.latest, defaultPost)) }, [])
 const submit = () => { const value = text.trim(); if (!value) return; const next = { ...defaultPost, text: value, timeAgo: "právě teď" }; setLatest(next); writeStorage(storageKeys.latest, next); setText("") }
 const onKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === "Enter" && !event.shiftKey && !event.nativeEvent.isComposing && event.keyCode !== 229) { event.preventDefault(); submit() } }
 const posts = [latest, ...demoPosts].filter((post) => (category === "všechno" || post.category === category) && (!query || post.text.toLowerCase().includes(query.toLowerCase()) || categoryLabels[post.category].toLowerCase().includes(query.toLowerCase())))
 return <main className="min-h-screen bg-[#071518] text-white"><SiteHeader /><div className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-14"><section className="mx-auto max-w-3xl text-center"><p className="text-xs uppercase tracking-[.3em] text-amber-100/60">Tiché místo uvnitř hlučného internetu</p><h1 className="mt-5 font-serif text-4xl leading-tight text-amber-50 md:text-6xl">Tady můžeš být sám sebou.</h1><p className="mt-4 text-lg text-white/55">Napiš, co máš v sobě. Bez jména. Bez soudu.</p></section><section id="composer" className="mx-auto mt-10 max-w-2xl"><AnonymousInput value={text} onChange={setText} onSubmit={submit} onKeyDown={onKeyDown} /></section><div className="mx-auto mt-10 flex max-w-5xl flex-col gap-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><h2 className="font-serif text-2xl text-amber-50">Příběhy lidí jako ty</h2><label className="flex items-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-4 py-2 text-sm text-white/45"><Search className="size-4" /><span className="sr-only">Hledat příběhy</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Hledat" className="w-28 bg-transparent outline-none placeholder:text-white/35" /></label></div><div className="flex gap-2 overflow-x-auto pb-2">{(["všechno", "vypsat", "podpora", "uspechy", "radosti", "vděčnost"] as const).map((item) => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-full border px-4 py-2 text-xs transition ${category === item ? "border-amber-100/50 bg-amber-100/10 text-amber-100" : "border-white/10 text-white/50 hover:text-white"}`}>{categoryLabels[item]}</button>)}</div><div className="grid gap-4 md:grid-cols-2">{posts.map((post) => <PostCard key={post.id} post={post} />)}</div>{posts.length === 0 && <p className="rounded-2xl border border-white/10 p-10 text-center text-white/45">Nic jsme nenašli.</p>}</div></div><footer className="border-t border-white/10 px-5 py-6"><SafetyBar /></footer></main> }
